services:
  bambu-p1s-mobile:
    image: ghcr.io/rico001/bambu-p1s-mobile:latest
    container_name: bambu-p1s-mobile
    ports:
      - "3003:3000" #change to your desired port(s)
    environment:
      - TASMOTA_SWITCH_IP=192.168.178.100 #change to your Tasmota switch IP
      - PRINTER_SERIAL_NUMBER= #change to your printer serial number
      - PRINTER_IP=192.168.178.79 #change to your printer IP
      - PRINTER_VIDEO_PORT=6000
      - PRINTER_MQTT_PORT=8883
      - PRINTER_FTP_PORT=990
      - PRINTER_USER=bblp
      - PRINTER_ACCESS_CODE=88223979 #change to your printer access code
      - PRINTER_CA_CERT_PATH=cert/blcert.pem
      - OFFLINE_DETECTION_TIMEOUT_MS=10000
      - OFFLINE_DETECTION_INTERVAL_MS=5000
      - PUPPETEER_HEADLESS=true
      - SERVER_PORT=3000 #change to your desired port
      - PRINTER_ERRORS_WHITELIST=0500-C011
      - THIRD_PARTY_IFRAME_TOGGLE_SRC=http://portainer-my-apps.fritz.box:5000/?deviceId=6827c4887ea5ad00133d18d6 #if set a icon in printersteam is shown for open this iframe
    restart: unless-stopped
    volumes:
      - ./thumbnails:/app/thumbnails