services:
  bambu-p1s-mobile:
    image: ghcr.io/rico001/bambu-p1s-mobile:latest
    container_name: bambu-p1s-mobile
    ports:
      - "3003:3000" #change to your desired port(s)
    environment:
      - PRINTER_SERIAL_NUMBER= #change to your printer serial number
      - PRINTER_IP=192.168.178.79 #change to your printer IP
      - PRINTER_VIDEO_PORT=6000
      - PRINTER_MQTT_PORT=8883
      - PRINTER_FTP_PORT=990
      - PRINTER_USER=bblp
      - PRINTER_ACCESS_CODE=88223979 #change to your printer access code
      - PRINTER_CA_CERT_PATH=cert/blcert.pem
      - PUPPETEER_HEADLESS=true
      - SERVER_PORT=3000 #change to your desired port
    restart: unless-stopped