services:
  p1stream:
    image: ghcr.io/rico001/bambu-http-2-mqtt-proxy/p1stream-main:latest
    container_name: p1stream
    ports:
      - "1984:1984"
      - "8554:8554"
    environment:
      PRINTER_ADDRESS: "192.168.178.79"
      PRINTER_ACCESS_CODE: "88223979"
    restart: unless-stopped

  bambu-p1s-mobile:
    image: ghcr.io/rico001/bambu-p1s-mobile:latest
    container_name: bambu-p1s-mobile
    ports:
      - "3003:3000"
    environment:
      - MQTT_BROKER_ADDRESS=mqtts://192.168.178.79:8883
      - MQTT_USERNAME=bblp
      - MQTT_PASSWORD=88223979
      - FTP_HOST=192.168.178.79
      - FTP_USER=bblp
      - FTP_PASSWORD=88223979
      - FTP_PORT=990
      - FTP_SECURE=implicit
      - PRINTER_SERIAL_NUMBER=01P00C4C0800240
      - PRINTER_CA_CERT_PATH=cert/blcert.pem
      - VIDEO_STREAM_URL=http://p1stream:1984/api/stream.mjpeg?src=p1s
      - PUPPETEER_HEADLESS=true
      - SERVER_PORT=3000
    restart: unless-stopped