version: "3.8"
#https://github.com/kurim/P1Stream
#http://localhost:1984/stream.html?src=p1s
services:
  p1stream:
    image: p1stream
    container_name: p1stream
    ports:
      - "1984:1984"
      - "8554:8554"
    environment:
      PRINTER_ADDRESS: "192.168.178.79"
      PRINTER_ACCESS_CODE: "88223979"
    restart: unless-stopped