version: '3.8'
# to get ids: ls -l /dev/v4l/by-id
services:
  webcam-stream0:
    image: mjpg-streamer-custom
    container_name: webcam-stream0
    restart: always
    devices:
      #- /dev/video0:/dev/video0
       - /dev/v4l/by-id/usb-Sonix_Technology_Co.__Ltd._Terra_HD1080PC_Camera_SN0001-video-index0:/dev/video0 # Terra 1080p
    ports:
      - "8080:8080"
    environment:
      FRAMERATE: 10
      RESOLUTION: "1920x1080"
      DEVICE: "/dev/video0"
      PORT: 8080

  webcam-stream1:
    image: mjpg-streamer-custom
    container_name: webcam-stream1
    restart: always
    devices:
      #- /dev/video1:/dev/video0  # map host video1 to container video0
      - /dev/v4l/by-id/usb-046d_C270_HD_WEBCAM_200901010001-video-index0:/dev/video0 # Logitech C270
    ports:
      - "8081:8080"
    environment:
      FRAMERATE: 10
      RESOLUTION: "1920x1080"
      DEVICE: "/dev/video0"
      PORT: 8080
