services:

  #debug on host: 
  #ls -l /dev/v4l/by-id
  #v4l2-ctl --list-formats-ext -d /dev/video<NUMMER>

  mjpg-streamer-0:
    image: mjpg-streamer-custom:latest
    container_name: mjpg-streamer-0
    devices:
      # C270: nur video-index0 ist wichtig, da nur dieses Capture kann
      - "/dev/v4l/by-id/usb-046d_C270_HD_WEBCAM_200901010001-video-index0:/dev/video0"
    security_opt:
      - no-new-privileges:true
    environment:
      CAMERA_DEV: /dev/video0
      # C270 unterstützt YUYV max. 640x480
      MJPEG_STREAMER_INPUT: "-y -r 1920x1080"
    ports:
      - "8080:8080"
    restart: unless-stopped

  mjpg-streamer-1:
    image: mjpg-streamer-custom:latest
    container_name: mjpg-streamer-1
    devices:
      # Sonix: video-index0 ist wichtig, da nur dieses Capture kann
      - "/dev/v4l/by-id/usb-Sonix_Technology_Co.__Ltd._Terra_HD1080PC_Camera_SN0001-video-index0:/dev/video0"
    security_opt:
      - no-new-privileges:true
    environment:
      CAMERA_DEV: /dev/video0
      # Sonix kann MJPEG 1920x1080
      MJPEG_STREAMER_INPUT: "-n -r 1920x1080 -f mjpeg"
    ports:
      - "8081:8080"
    restart: unless-stopped