name: Build & Push App Image
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/src/**'
      - 'src/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'App-Version (wenn leer, aus package.json)'
        required: false
        default: ''
      push:
        description: 'Image wirklich pushen? (true/false)'
        required: true
        default: 'true'
      branch:
        description: 'Branch, der ausgecheckt wird'
        required: false
        default: 'main'

permissions:
  contents: read
  packages: write

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Bestimme App-Version-Tag
        id: set_tag
        run: |
          if [ "${{ github.event.inputs.version }}" != "" ]; then
            TAG=${{ github.event.inputs.version }}
          else
            TAG=$(node -p "require('./package.json').version")
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Push App Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event.inputs.push == 'true' }}
          tags: |
            ghcr.io/${{ github.actor }}/bambu-p1s-mobile:${{ env.TAG }}
            ghcr.io/${{ github.actor }}/bambu-p1s-mobile:latest
