name: Build & Push P1Stream Image

on:
  push:
    branches:
      - main
      - restructure-project
    paths:
      - 'p1stream-main/Dockerfile'
      - 'p1stream-main/version.txt'
      - '.github/workflows/build-p1-stream-image.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-p1stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read P1_STREAM_VERSION
        id: get_p1_version
        run: |
          P1_STREAM_VERSION=$(cat p1stream-main/version.txt)
          echo "P1_STREAM_VERSION=$P1_STREAM_VERSION" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Push P1Stream Image
        uses: docker/build-push-action@v4
        with:
          context: ./p1stream-main
          file: ./p1stream-main/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/p1stream-main:latest
            ghcr.io/${{ github.repository }}/p1stream-main:${{ env.P1_STREAM_VERSION }}
