name: Build & Push Docker Images

# löst aus bei Push auf main oder restructure-project, wenn sich Dockerfiles oder package.json ändern
on:
  push:
    branches:
      - main
      - restructure-project
    paths:
      - 'Dockerfile'
      - 'P1Stream-main/Dockerfile'
      - 'package.json'
  workflow_dispatch:

# damit wir das GITHUB_TOKEN zum Pushen in die Registry nutzen dürfen
permissions:
  contents: read    # checkout
  packages: write   # Container Registry

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Code auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Node.js, um später die Version zu parsen
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3) Version aus package.json holen (ohne verschachtelte Quotes)
      - name: Read package.json version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # 4) Login in GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5) QEMU (optional für Multi-Arch)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 6) Buildx aktivieren
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 7) Root-Image bauen & pushen
      - name: Build & Push root image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}

      # 8) P1Stream-Main-Image bauen & pushen
      - name: Build & Push P1Stream-main image
        uses: docker/build-push-action@v4
        with:
          context: ./P1Stream-main
          file: ./P1Stream-main/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/p1stream-main:latest
            ghcr.io/${{ github.repository }}/p1stream-main:${{ env.VERSION }}
