name: Build & Push App Image

on:
  push:
    branches:
      - main
      - develop
      - ts-backend-support
    paths:
      - 'Dockerfile'
      - 'package.json'
      - '.github/workflows/build-app-image.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Read app version
        id: get_app_version
        run: |
          APP_VERSION=$(node -p "require('./package.json').version")
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Push App Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:
            - ghcr.io/${{ github.actor }}/p1-mobile:${{ github.ref_name }}-latest
            - ghcr.io/${{ github.actor }}/p1-mobile:${{ github.ref_name }}-${{ env.APP_VERSION }}
