name: Build & Push App Image

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '.github/workflows/build-external-videostream-image.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Push App Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./webcam-external-stream/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/external-videostream:${{ github.ref_name }}-latest
