name: Build & Push Docker Images

on:
  push:
    branches:
      - main
      - restructure-project
    paths:
      - 'Dockerfile'
      - 'package.json'
      - 'p1stream-main/Dockerfile'
      - 'p1stream-main/version.txt'
  workflow_dispatch:

permissions:
  contents: read 
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Read root version
        id: get_root_version
        run: |
          ROOT_VERSION=$(node -p "require('./package.json').version")
          echo "ROOT_VERSION=$ROOT_VERSION" >> $GITHUB_ENV

      - name: Read p1stream-main version
        id: get_p1_version
        run: |
          P1_STREAM_VERSION=$(cat p1stream-main/version.txt)
          echo "P1_STREAM_VERSION=$P1_STREAM_VERSION" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Push root image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/bambu-p1s-mobile:latest
            ghcr.io/bambu-p1s-mobile:${{ env.ROOT_VERSION }}

      - name: Build & Push p1stream-main image
        uses: docker/build-push-action@v4
        with:
          context: ./p1stream-main
          file: ./p1stream-main/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/p1stream-main:latest
            ghcr.io/${{ github.repository }}/p1stream-main:${{ env.P1_STREAM_VERSION }}
